### ISSUE TITLE
[Bug] RFC3986 Reserved Characters not properly encoding with URL Encoder

### ISSUE THREAD

**Issue by Seralahthan** [wso2-cs/cs-tools#2]
### **Issue**

Current implementation of the `URL Encoder` doesn't properly encode [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#page-13) specified `reserved characters`: `!`, `'`, `(`, `)` and `*`.

> unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
> reserved    = gen-delims / sub-delims
> gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
> sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

For example, if we have a string like `apple!(123`, following are the url-encoded strings returned from the current URL encoder and the [URLEncoder.Org](https://www.urlencoder.org/),
```
String = apple!(123
URL Encoded String from current URL Encoder = apple!(123
URL Encoded String from URLEncoder.Org = apple%21%28123
```
<img width="1709" alt="Screenshot 2024-09-10 at 11 39 57 PM" src="https://github.com/user-attachments/assets/f008341f-e3a1-49c1-ac61-4e8eeca8c52b">
<img width="622" alt="Screenshot 2024-09-10 at 11 40 15 PM" src="https://github.com/user-attachments/assets/e7cb04fb-3ab0-4895-a458-112c59e7a065">

### **Analysis**

This happens as the current implementation of the URL Encoder is using `built-in` Javascript function `encodeURIComponent()`. 

```javascript
function urlEncode(){
    get('preUrlOutputCode').innerText = encodeURIComponent(get('textAreaUrlInput').value);
}
```

The `encodeURIComponent()` JS function escapes all characters in a string while performing url-encoding, `except`:
```
A–Z a–z 0–9 - _ . ! ~ * ' ( )
```
characters as per the [spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#description) document.

URL Encoder implementation needs to be modified to make it compatible with [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#page-13)

**Comment by dineshjweerakkody** [comment]
Thanks Sera for reporting this and sending a PR with the fix. I merged the PR and closing the issue.
